openapi: 3.0.3
info:
  title: REST API For Access To TURN Services
  description: Describes a proposed standard REST API for obtaining
    access to TURN services via ephemeral (i.e. time-limited)
    credentials.  These credentials are vended by a web service over
    HTTP, and then supplied to and checked by a TURN server using the
    standard TURN protocol.
  version: 0.0.1
servers:
  - url: /
tags:
  - name: TURN
    description:  To retrieve a new set of credentials, the client makes a HTTP GET
      request, specifying TURN as the service to allocate credentials for,
      and optionally specifying a user id parameter.
    externalDocs:
      url: https://datatracker.ietf.org/doc/html/draft-uberti-rtcweb-turn-rest-00
  - name: ICE
paths:
  /:
    get:
      tags:
        - TURN
      summary: GET TURN credentials
      description: GET request, specifying TURN as the service to allocate credentials for, and optionally specifying a user id parameter.
      operationId: getTurnAuth
      parameters:
        - name: service
          in: query
          description: Specifies the desired service (turn)
          required: true
          schema:
            type: string
            enum:
              - turn
            default: turn
        - name: username
          in: query
          description:  An optional user id to be associated with the credentials
          required: false
          schema:
            type: string
        - name: ttl
          in: query
          description: Duration for the lifetime of the authentication token, in seconds.
          required: false
          schema:
            type: integer
            default: 86400
        - name: key
          in: query
          description: If an API key is used for authentication, the API key
          required: false
          schema:
            type: string
        - name: namespace
          in: query
          description: |
            Generate TURN URIs only for the Gateways in the given namespace (optional)
          required: false
          schema:
            type: string
        - name: gateway
          in: query
          description: |
            Generate TURN URIs only for the specified Gateway (optional); if gateway is set then
            namespace must be set as well
          required: false
          schema:
            type: string
        - name: listener
          in: query
          description: |
            Generate TURN URIs only for the specified listener of a given Gateway (optional); if
            listener is set then namespace and gateway must be set as well
          required: false
          schema:
            type: string
        - name: public-addr
          in: query
          description: Override the public IP address with the provided value (optional)
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/turnAuthenticationToken'
        "400":
          description: Invalid status value
  /ice:
    get:
      tags:
        - ICE
      summary: GET ICE credentials
      description: GET request, specifying TURN as the service to allocate credentials for, and optionally specifying a user id parameter.
      operationId: getIceAuth
      parameters:
        - name: service
          in: query
          description: Specifies the desired service (optional, turn)
          required: false
          schema:
            type: string
            enum:
              - turn
            default: turn
        - name: username
          in: query
          description: An optional user id to be associated with the credentials
          required: false
          schema:
            type: string
        - name: ttl
          in: query
          description: Duration for the lifetime of the authentication token, in seconds.
          required: false
          schema:
            type: integer
            default: 86400
        - name: iceTransportPolicy
          in: query
          description: An optional ICE transport policy ("all", "public", "relay").
          required: false
          schema:
            $ref: '#/components/schemas/iceTransportPolicy'
        - name: key
          in: query
          description: If an API key is used for authentication, the API key
          required: false
          schema:
            type: string
        - name: namespace
          in: query
          description: |
            Generate TURN URIs only for the Gateways in the given namespace (optional)
          required: false
          schema:
            type: string
        - name: gateway
          in: query
          description: |
            Generate TURN URIs only for the specified Gateway (optional); if gateway is set then
            namespace must be set as well
          required: false
          schema:
            type: string
        - name: listener
          in: query
          description: |
            Generate TURN URIs only for the specified listener of a given Gateway (optional); if
            listener is set then namespace and gateway must be set as well
          required: false
          schema:
            type: string
        - name: public-addr
          in: query
          description: Override the public IP address with the provided value (optional)
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iceConfig'
        "400":
          description: Invalid status value
components:
  schemas:
    turnAuthenticationToken:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        ttl:
          type: integer
          format: int64
        uris:
          type: array
          items:
            type: string
      example:
        username: 12334939:username
        password: randomHashedPassword
        ttl: 86400
        uris:
          - turn:1.2.3.4:9991?transport=udp
          - turn:1.2.3.4:9992?transport=tcp
          - turns:1.2.3.4:443?transport=tcp
    iceAuthenticationToken:
      type: object
      properties:
        username:
          type: string
        credential:
          type: string
        urls:
          type: array
          items:
            type: string
      example:
        username: 12334939:username
        credential: randomHashedPassword
        urls:
          - turn:1.2.3.4:9991?transport=udp
          - turn:1.2.3.4:9992?transport=tcp
          - turns:1.2.3.4:443?transport=tcp
    iceTransportPolicy:
      type: string
      enum:
        - all
        - public
        - relay
      default: all
    iceConfig:
      type: object
      properties:
        iceServers:
          type: array
          items:
            "$ref": "#/components/schemas/iceAuthenticationToken"
        iceTransportPolicy:
          "$ref": "#/components/schemas/iceTransportPolicy"
      example:
        iceServers:
          - username: 12334939:username
            credential: randomHashedPassword
            urls:
              - turn:1.2.3.4:9991?transport=udp
              - turn:1.2.3.4:9992?transport=tcp
              - turns:1.2.3.4:443?transport=tcp
          - username: 987654321:othername
            credential: someOtherHashedPassword
            urls:
              - turn:1.2.3.4:3478?transport=tcp
        iceTransportpolicy: relay
